---
galaxy_info:
  author: Gui Hecheng
  description: Config Keepalived
  license: Apache
  min_ansible_version: 2.3
  platforms:
    - name: EL
      versions:
        - 7
  categories:
    - system
dependencies: []
